version: '2.1'
orbs:
  mvnw: ayte/mvnw@0.1.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0
    working_directory: /tmp/workspace
    steps:
      - checkout
      - mvnw/circle:
          command: clean clover:setup test install clover:aggregate
      - persist_to_workspace:
          root: /tmp/workspace
          paths: ['*', '**/*']

  analyze:
    docker:
      - image: circleci/openjdk:11.0
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - mvnw/circle:
          command: sonar:sonar

  report:
    docker:
      - image: circleci/openjdk:8
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - mvnw/circle:
          command: allure:report clover:clover
      - store_artifacts:
          path: target/site/clover
          destination: Report/Clover
      - store_artifacts:
          path: target/site/allure
          destination: Report/Allure
  stage:
    docker:
        - image: circleci/openjdk:11.0
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          echo 'Package: libassuan0' | sudo tee /etc/apt/preferences.d/libassuan0
          echo 'Pin: release n=stretch-backports' | sudo tee -a /etc/apt/preferences.d/libassuan0
          echo 'Pin-Priority: 1000' | sudo tee -a /etc/apt/preferences.d/libassuan0
      - run: sudo apt-get install gpg gpg-agent
      - run: echo "$GPG_SECRET_KEY" | base64 -d > /tmp/key
      - run: echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --import /tmp/key
      - run: rm /tmp/key
      - run: sudo ln -s $(which gpg) /usr/local/bin/gpg2
      - mvnw/circle:
          command: package gpg:sign nexus-staging:deploy
  release:
    docker:
      - image: circleci/openjdk:11.0
    working_directory: /tmp/workspace
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
          echo 'Package: libassuan0' | sudo tee /etc/apt/preferences.d/libassuan0
          echo 'Pin: release n=stretch-backports' | sudo tee -a /etc/apt/preferences.d/libassuan0
          echo 'Pin-Priority: 1000' | sudo tee -a /etc/apt/preferences.d/libassuan0
      - run: sudo apt-get install gpg gpg-agent
      - run: echo "$GPG_SECRET_KEY" | base64 -d > /tmp/key
      - run: echo "$GPG_PASSPHRASE" | gpg --batch --yes --passphrase-fd 0 --import /tmp/key
      - run: rm /tmp/key
      - run: sudo ln -s $(which gpg) /usr/local/bin/gpg2
      - mvnw/circle:
          command: package gpg:sign nexus-staging:deploy nexus-staging:release

workflows:
  version: '2.1'
  default:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - analyze:
          requires:
            - build
          filters:
            tags:
              only: /.*/
          context: sonarcloud.io
      - report:
          requires:
            - build
          filters:
            tags:
              only: /.*/
      - stage:
          requires:
            - build
          context: sonatype.org
          filters:
            branches:
              only: /.*/
            tags:
              ignore: /.*/
      - release:
          requires:
            - build
          context: sonatype.org
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /\d+\.\d+\.\d+/
